// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmYl7jfIfqSECkhNdEL9bTB-8dUkZkXUA',
    appId: '1:176901515929:web:863c0991469ca77ec3e608',
    messagingSenderId: '176901515929',
    projectId: 'mynagalaga',
    authDomain: 'mynagalaga.firebaseapp.com',
    storageBucket: 'mynagalaga.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo_1RiXPR4WskRmRwIs_sbOTeb3UUq3I0',
    appId: '1:176901515929:android:7eb0328c218f885ec3e608',
    messagingSenderId: '176901515929',
    projectId: 'mynagalaga',
    storageBucket: 'mynagalaga.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDICTE2ZvPeEYGFliVn3TSQ1XvM8UpPqb4',
    appId: '1:176901515929:ios:4ee60f5273510122c3e608',
    messagingSenderId: '176901515929',
    projectId: 'mynagalaga',
    storageBucket: 'mynagalaga.firebasestorage.app',
    iosBundleId: 'com.example.mynagalagaMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDICTE2ZvPeEYGFliVn3TSQ1XvM8UpPqb4',
    appId: '1:176901515929:ios:4ee60f5273510122c3e608',
    messagingSenderId: '176901515929',
    projectId: 'mynagalaga',
    storageBucket: 'mynagalaga.firebasestorage.app',
    iosBundleId: 'com.example.mynagalagaMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmYl7jfIfqSECkhNdEL9bTB-8dUkZkXUA',
    appId: '1:176901515929:web:f5030ddfca85a78cc3e608',
    messagingSenderId: '176901515929',
    projectId: 'mynagalaga',
    authDomain: 'mynagalaga.firebaseapp.com',
    storageBucket: 'mynagalaga.firebasestorage.app',
  );
}
