// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdVSuWfqoyorAn7p1xYLONNpAIVM-SFVs',
    appId: '1:165350345023:web:84a24643983bd8b5526b8a',
    messagingSenderId: '165350345023',
    projectId: 'mynagalaga-2fb62',
    authDomain: 'mynagalaga-2fb62.firebaseapp.com',
    storageBucket: 'mynagalaga-2fb62.firebasestorage.app',
    measurementId: 'G-P2TM12463E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM_YeUkQbElQJ5oLJGWDsXi_K0O6TXmVU',
    appId: '1:165350345023:android:7d7e5f9f213ccf67526b8a',
    messagingSenderId: '165350345023',
    projectId: 'mynagalaga-2fb62',
    storageBucket: 'mynagalaga-2fb62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2x6RBIeReV4jVop70JEGR-Pp16xa-ovQ',
    appId: '1:165350345023:ios:724930f2fb37aac6526b8a',
    messagingSenderId: '165350345023',
    projectId: 'mynagalaga-2fb62',
    storageBucket: 'mynagalaga-2fb62.firebasestorage.app',
    iosBundleId: 'com.example.mynagalagaMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2x6RBIeReV4jVop70JEGR-Pp16xa-ovQ',
    appId: '1:165350345023:ios:724930f2fb37aac6526b8a',
    messagingSenderId: '165350345023',
    projectId: 'mynagalaga-2fb62',
    storageBucket: 'mynagalaga-2fb62.firebasestorage.app',
    iosBundleId: 'com.example.mynagalagaMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdVSuWfqoyorAn7p1xYLONNpAIVM-SFVs',
    appId: '1:165350345023:web:bb7f4122bda62cfe526b8a',
    messagingSenderId: '165350345023',
    projectId: 'mynagalaga-2fb62',
    authDomain: 'mynagalaga-2fb62.firebaseapp.com',
    storageBucket: 'mynagalaga-2fb62.firebasestorage.app',
    measurementId: 'G-1TENVS929X',
  );

}